In [1]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
iris_data = iris.data # 독립변수
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
iris_target = iris.target # 종속변수

In [5]:
# iris.target_names[iris.target]

In [6]:
# 실습형 1. 각 변수별 평균
np.mean(iris_data, axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [18]:
# 2. 처음 다섯개 행
q2 = iris_data[:5,]
q2

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
# 3. 처음 다섯개 행 + 마지막 열 제외
q3 = iris_data[:5,:-1]
q3

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [15]:
# 4. 처음 다섯개 행 + 마지막 열만
q4 = iris_data[:5,-1:]
q4

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

In [17]:
# 5. 3번 배열과 4번 배열을 합치기
q5 = np.hstack((q3, q4))
q5

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [33]:
# 6. 처음 다섯개 행 + 각 열별 평균보다 큰 값들만
q2 = iris_data[:5,]
q6 = q2[q2 > np.mean(q2, axis=0)]
q6

array([5.1, 3.5, 4.9, 1.5, 5. , 3.6])

In [40]:
# 풀이형 1. print(a.sum(0)) 결과는?
# ③ [12 15 18 21]
a = np.arange(12).reshape(3,4)
print(a.sum(0))

[12 15 18 21]


In [46]:
# 2. a 데이터의 차원을 바꿀수 있는 방법이 아닌것은?
# ④ a,T(4,3)
a = np.floor(10*np.random.random((3,4)))
a.shape
a.T

array([[4., 6., 4.],
       [7., 3., 4.],
       [5., 0., 6.],
       [2., 3., 9.]])

In [49]:
# 3. 첫번째 행과 두번째 행만 뽑고 싶을 때
# ① a[:2]
a = np.arange(12).reshape(3,4)
print(a[:2])
print(a[:,:2])
print(a[1,2])
print(a[1][2])

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]
6
6


In [50]:
# 4. 실행 결과
# ④ 오류 a[1,3,4]=0 으로 수정해야함 -----> 틀림
a = np.array([1,2,3,4,5])
a[[1,3,4]] = 0
a

array([1, 0, 3, 0, 0])

In [53]:
# 5. 빈칸에 입력할 것
# ② np.c_[a, b]
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.c_[a, b]

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])